### ISSUE TITLE
Patches synchornized from cupy PR?

### ISSUE THREAD

**Issue by Berrysoft** [Azusachan/python-cupy-rocm#3]
I've noticed your PR for cupy and also found that you are the maintainer of `python-cupy-rocm` AUR script.

https://github.com/cupy/cupy/pull/8319#issuecomment-2127033251

Here @littlewu2508 and I proposed a patch to solve the soft link errors. Actually we tried your patch on Gentoo and found the bug. You may need to try on Arch yourself because I don't have an Arch machine with AMD GPU.

https://github.com/cupy/cupy/pull/8319#discussion_r1611964916

Here is a small suggestion.

**Comment by Azusachan** [comment]
I will try on my arch machine later this week, thanks for your patch!

From iOS Outlook<https://aka.ms/qtex0l>

________________________________
From: 王宇逸 ***@***.***>
Sent: Wednesday, May 29, 2024 3:57:29 AM
To: Azusachan/python-cupy-rocm ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Azusachan/python-cupy-rocm] Patches synchornized from cupy PR? (Issue #3)


I've noticed your PR for cupy and also found that you are the maintainer of python-cupy-rocm AUR script.

cupy/cupy#8319 (comment)<https://github.com/cupy/cupy/pull/8319#issuecomment-2127033251>

Here @littlewu2508<https://github.com/littlewu2508> and I proposed a patch to solve the soft link errors. Actually we tried your patch on Gentoo and found the bug. You may need to try on Arch yourself because I don't have an Arch machine with AMD GPU.

cupy/cupy#8319 (comment)<https://github.com/cupy/cupy/pull/8319#discussion_r1611964916>

Here is a small suggestion.
